-- reservation_number, flight_number, flight_date, leg --
INSERT INTO RESERVATION_DETAIL('00001', '002', to_date('12-04-2016'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00002', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00003', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00003', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00003', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00003', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00004', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00005', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00005', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00005', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00006', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00006', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00006', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00006', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00007', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00007', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00007', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00007', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00008', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00009', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00009', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00009', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00010', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00010', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00010', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00010', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00011', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00011', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00011', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00011', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00012', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00012', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00013', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00013', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00013', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00014', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00015', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00015', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00016', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00017', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00017', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00017', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00018', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00018', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00018', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00019', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00020', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00020', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00020', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00020', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00021', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00021', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00021', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00022', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00022', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00023', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00023', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00024', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00024', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00025', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00025', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00025', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00026', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00026', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00026', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00027', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00027', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00027', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00028', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00028', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00028', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00028', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00029', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00029', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00030', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00031', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00032', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00032', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00032', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00032', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00033', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00033', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00034', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00035', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00035', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00036', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00037', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00037', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00037', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00038', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00039', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00039', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00040', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00040', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00040', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00040', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00041', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00041', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00041', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00041', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00042', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00042', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00042', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00043', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00043', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00043', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00043', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00044', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00045', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00046', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00046', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00047', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00047', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00047', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00048', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00048', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00048', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00048', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00049', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00049', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00050', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00051', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00051', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00052', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00052', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00052', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00052', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00053', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00054', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00054', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00055', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00055', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00055', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00056', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00057', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00057', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00057', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00057', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00058', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00058', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00058', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00059', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00059', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00059', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00059', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00060', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00060', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00060', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00061', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00062', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00063', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00063', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00063', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00063', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00064', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00064', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00064', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00064', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00065', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00065', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00065', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00066', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00066', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00067', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00067', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00068', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00068', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00068', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00069', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00069', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00070', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00070', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00070', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00071', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00071', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00072', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00072', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00073', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00073', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00073', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00073', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00074', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00074', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00074', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00075', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00075', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00075', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00075', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00076', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00076', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00076', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00077', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00077', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00078', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00078', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00078', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00079', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00079', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00079', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00080', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00080', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00081', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00081', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00081', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00081', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00082', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00082', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00082', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00083', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00083', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00083', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00084', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00085', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00085', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00086', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00087', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00088', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00088', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00088', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00089', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00090', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00090', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00090', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00090', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00091', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00092', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00092', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00093', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00093', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00094', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00094', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00095', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00095', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00095', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00095', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00096', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00096', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00097', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00098', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00098', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00099', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00099', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00099', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00099', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00100', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00101', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00101', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00101', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00101', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00102', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00103', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00103', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00103', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00104', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00104', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00104', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00105', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00105', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00105', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00105', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00106', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00106', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00107', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00107', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00108', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00109', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00109', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00109', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00110', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00110', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00110', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00110', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00111', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00112', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00112', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00112', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00113', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00114', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00114', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00114', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00115', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00115', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00116', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00116', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00116', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00116', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00117', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00118', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00118', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00119', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00119', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00120', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00120', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00120', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00120', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00121', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00121', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00121', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00122', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00122', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00123', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00124', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00124', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00125', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00125', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00125', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00125', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00126', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00126', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00127', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00128', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00128', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00129', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00129', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00130', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00130', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00130', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00131', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00131', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00131', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00131', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00132', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00132', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00133', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00133', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00134', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00134', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00135', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00136', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00136', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00137', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00137', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00138', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00138', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00139', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00139', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00139', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00140', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00141', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00141', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00141', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00142', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00142', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00143', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00144', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00145', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00145', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00145', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00146', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00146', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00146', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00147', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00147', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00147', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00147', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00148', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00149', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00149', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00149', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00150', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00150', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00151', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00151', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00152', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00152', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00153', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00153', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00153', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00153', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00154', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00154', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00155', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00155', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00155', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00156', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00156', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00156', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00157', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00157', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00157', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00158', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00158', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00158', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00159', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00159', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00160', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00160', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00161', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00162', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00162', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00162', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00162', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00163', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00163', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00163', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00163', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00164', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00164', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00164', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00165', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00165', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00165', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00165', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00166', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00166', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00167', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00167', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00167', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00168', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00168', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00168', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00168', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00169', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00170', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00170', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00170', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00170', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00171', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00171', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00171', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00172', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00173', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00173', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00173', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00173', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00174', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00174', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00174', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00175', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00175', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00175', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00176', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00177', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00177', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00178', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00179', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00179', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00180', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00181', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00182', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00182', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00182', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00182', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00183', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00184', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00185', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00186', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00187', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00188', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00188', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00188', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00189', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00190', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00190', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00190', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00191', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00191', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00192', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00193', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00193', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00193', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00194', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00195', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00195', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00196', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00197', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00197', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00197', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00197', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00198', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00198', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00198', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00199', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00199', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00199', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00200', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00200', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00200', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00201', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00202', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00202', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00202', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00202', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00203', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00203', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00203', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00204', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00204', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00204', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00205', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00205', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00206', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00206', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00206', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00206', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00207', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00208', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00208', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00209', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00209', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00210', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00210', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00211', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00211', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00211', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00212', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00212', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00212', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00212', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00213', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00214', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00215', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00216', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00216', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00216', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00217', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00217', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00217', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00217', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00218', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00218', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00218', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00219', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00220', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00220', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00220', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00221', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00221', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00221', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00222', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00222', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00222', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00223', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00224', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00224', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00224', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00224', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00225', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00225', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00225', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00226', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00226', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00227', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00228', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00229', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00229', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00229', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00229', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00230', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00230', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00230', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00230', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00231', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00232', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00232', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00232', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00233', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00233', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00233', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00233', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00234', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00234', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00234', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00235', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00236', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00236', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00237', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00237', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00237', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00237', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00238', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00238', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00238', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00238', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00239', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00240', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00241', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00242', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00243', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00243', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00243', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00243', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00244', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00245', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00245', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00245', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00246', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00246', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00246', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00246', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00247', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00247', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00247', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00247', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00248', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00248', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00248', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00248', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00249', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00250', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00250', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00250', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00250', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00251', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00251', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00251', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00252', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00253', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00253', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00254', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00254', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00254', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00255', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00255', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00255', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00256', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00256', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00257', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00258', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00258', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00258', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00258', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00259', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00259', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00259', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00260', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00261', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00261', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00261', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00262', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00263', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00263', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00263', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00263', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00264', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00264', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00265', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00266', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00266', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00267', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00267', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00267', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00267', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00268', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00268', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00268', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00269', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00269', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00270', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00270', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00271', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00271', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00271', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00272', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00272', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00273', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00273', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00273', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00273', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00274', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00274', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00274', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00274', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00275', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00276', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00276', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00276', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00277', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00277', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00277', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00277', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00278', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00278', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00279', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00279', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00279', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00279', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00280', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00281', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00281', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00281', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00281', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00282', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00282', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00283', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00284', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00284', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00284', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00284', '<flight num>', 4 );
INSERT INTO RESERVATION_DETAIL('00285', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00285', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00286', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00287', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00288', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00289', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00290', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00290', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00291', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00291', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00292', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00292', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00293', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00293', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00294', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00295', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00295', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00296', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00296', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00297', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00297', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00298', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00298', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00299', '<flight num>', to_date('<%s>'), 'MM-DD-YYYY'), 1 );
INSERT INTO RESERVATION_DETAIL('00299', '<flight num>', 2 );
INSERT INTO RESERVATION_DETAIL('00299', '<flight num>', 3 );
INSERT INTO RESERVATION_DETAIL('00299', '<flight num>', 4 );
